name: Build Static Linux Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust with MUSL target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build statically linked binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-musl/release/grrs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

